read_blif fsm.blif
state_minimize stamina
state_assign nova
stg_to_network
resub
resub
eliminate -1
resub
collapse
collapse
collapse
espresso
simplify
source script.rugged
reduce_depth
reduce_depth
resub
collapse
reduce_depth
collapse
sweep
source script.rugged
reduce_depth
source script.rugged
simplify
espresso
espresso
simplify
simplify
full_simplify
sweep
resub
espresso
eliminate -1
resub
full_simplify
eliminate -1
reduce_depth
full_simplify
simplify
resub
simplify
reduce_depth
eliminate -1
full_simplify
full_simplify
full_simplify
reduce_depth
resub
collapse
source script.rugged
fx
source script.rugged
full_simplify
sweep
espresso
simplify
resub
sweep
espresso
source script.rugged
sweep
reduce_depth
eliminate -1
collapse
espresso
collapse
collapse
simplify
eliminate -1
fx
simplify
collapse
espresso
espresso
collapse
fx
fx
full_simplify
espresso
collapse
resub
full_simplify
simplify
simplify
resub
sweep
resub
source script.rugged
reduce_depth
fx
collapse
reduce_depth
collapse
full_simplify
resub
source script.rugged
collapse
espresso
simplify
fx
eliminate -1
sweep
reduce_depth
simplify
collapse
eliminate -1
espresso
resub
sweep
resub
source script.rugged
espresso
resub
full_simplify
fx
source script.rugged
fx
source script.rugged
collapse
reduce_depth
resub
espresso
simplify
sweep
sweep
source script.rugged
reduce_depth
source script.rugged
resub
resub
reduce_depth
simplify
write_blif min_fsm.blif
