read_blif fsm.blif
state_minimize
state_assign jedi
stg_to_network
resub
collapse
resub
simplify
collapse
espresso
collapse
full_simplify
source script.rugged
simplify
source script.rugged
collapse
espresso
resub
fx
full_simplify
fx
source script.rugged
simplify
sweep
eliminate -1
espresso
eliminate -1
full_simplify
sweep
resub
espresso
espresso
collapse
resub
resub
reduce_depth
full_simplify
collapse
sweep
eliminate -1
resub
source script.rugged
full_simplify
espresso
full_simplify
collapse
full_simplify
source script.rugged
source script.rugged
source script.rugged
sweep
resub
reduce_depth
full_simplify
sweep
sweep
simplify
collapse
reduce_depth
source script.rugged
fx
source script.rugged
resub
source script.rugged
reduce_depth
espresso
sweep
full_simplify
resub
sweep
resub
simplify
sweep
simplify
collapse
espresso
sweep
fx
collapse
reduce_depth
source script.rugged
fx
eliminate -1
fx
simplify
collapse
source script.rugged
eliminate -1
simplify
collapse
resub
full_simplify
fx
simplify
reduce_depth
simplify
sweep
eliminate -1
simplify
simplify
collapse
simplify
collapse
reduce_depth
reduce_depth
sweep
fx
resub
source script.rugged
collapse
fx
collapse
full_simplify
sweep
reduce_depth
resub
fx
espresso
source script.rugged
full_simplify
fx
espresso
sweep
collapse
simplify
collapse
fx
espresso
source script.rugged
fx
simplify
full_simplify
eliminate -1
resub
reduce_depth
resub
sweep
fx
collapse
eliminate -1
sweep
sweep
full_simplify
sweep
collapse
simplify
collapse
fx
full_simplify
source script.rugged
eliminate -1
reduce_depth
espresso
collapse
espresso
full_simplify
full_simplify
source script.rugged
reduce_depth
resub
full_simplify
source script.rugged
full_simplify
sweep
source script.rugged
simplify
reduce_depth
sweep
resub
eliminate -1
source script.rugged
eliminate -1
resub
resub
full_simplify
fx
collapse
fx
source script.rugged
resub
full_simplify
resub
fx
resub
espresso
sweep
eliminate -1
full_simplify
espresso
full_simplify
fx
full_simplify
collapse
fx
source script.rugged
sweep
reduce_depth
simplify
simplify
eliminate -1
fx
source script.rugged
source script.rugged
reduce_depth
simplify
resub
espresso
fx
espresso
espresso
simplify
full_simplify
reduce_depth
collapse
reduce_depth
espresso
fx
reduce_depth
sweep
simplify
resub
eliminate -1
full_simplify
espresso
collapse
sweep
reduce_depth
simplify
resub
espresso
simplify
reduce_depth
collapse
simplify
sweep
resub
resub
eliminate -1
resub
simplify
espresso
espresso
simplify
reduce_depth
eliminate -1
simplify
full_simplify
espresso
fx
simplify
espresso
fx
reduce_depth
full_simplify
simplify
reduce_depth
fx
simplify
eliminate -1
reduce_depth
sweep
sweep
sweep
collapse
source script.rugged
full_simplify
reduce_depth
espresso
source script.rugged
collapse
simplify
source script.rugged
source script.rugged
source script.rugged
full_simplify
reduce_depth
source script.rugged
simplify
fx
eliminate -1
fx
fx
source script.rugged
reduce_depth
resub
sweep
full_simplify
collapse
collapse
resub
reduce_depth
collapse
fx
fx
collapse
source script.rugged
espresso
source script.rugged
espresso
simplify
collapse
reduce_depth
reduce_depth
fx
fx
simplify
resub
fx
resub
full_simplify
reduce_depth
source script.rugged
collapse
espresso
eliminate -1
fx
source script.rugged
fx
reduce_depth
collapse
full_simplify
collapse
simplify
collapse
source script.rugged
full_simplify
eliminate -1
sweep
collapse
full_simplify
eliminate -1
simplify
full_simplify
collapse
reduce_depth
reduce_depth
simplify
reduce_depth
reduce_depth
fx
simplify
sweep
fx
sweep
resub
sweep
espresso
resub
fx
simplify
collapse
reduce_depth
simplify
simplify
reduce_depth
source script.rugged
fx
full_simplify
fx
sweep
resub
simplify
source script.rugged
simplify
sweep
full_simplify
eliminate -1
reduce_depth
reduce_depth
full_simplify
resub
espresso
fx
reduce_depth
source script.rugged
eliminate -1
fx
eliminate -1
sweep
full_simplify
fx
reduce_depth
collapse
collapse
fx
sweep
eliminate -1
reduce_depth
eliminate -1
reduce_depth
reduce_depth
espresso
fx
reduce_depth
full_simplify
fx
espresso
full_simplify
espresso
full_simplify
simplify
full_simplify
sweep
source script.rugged
fx
collapse
simplify
source script.rugged
eliminate -1
full_simplify
full_simplify
collapse
collapse
collapse
collapse
simplify
eliminate -1
fx
reduce_depth
eliminate -1
sweep
sweep
fx
simplify
source script.rugged
source script.rugged
full_simplify
espresso
simplify
collapse
espresso
espresso
espresso
resub
sweep
collapse
reduce_depth
fx
collapse
reduce_depth
simplify
sweep
collapse
collapse
reduce_depth
eliminate -1
collapse
simplify
sweep
simplify
espresso
full_simplify
source script.rugged
full_simplify
resub
eliminate -1
eliminate -1
eliminate -1
sweep
sweep
collapse
resub
resub
collapse
reduce_depth
simplify
simplify
reduce_depth
fx
full_simplify
simplify
reduce_depth
full_simplify
eliminate -1
source script.rugged
simplify
eliminate -1
full_simplify
eliminate -1
collapse
fx
simplify
collapse
eliminate -1
eliminate -1
full_simplify
reduce_depth
reduce_depth
espresso
reduce_depth
full_simplify
collapse
reduce_depth
simplify
simplify
sweep
reduce_depth
espresso
espresso
sweep
resub
fx
sweep
espresso
full_simplify
source script.rugged
reduce_depth
simplify
resub
source script.rugged
espresso
collapse
simplify
source script.rugged
sweep
sweep
source script.rugged
collapse
reduce_depth
reduce_depth
eliminate -1
source script.rugged
reduce_depth
full_simplify
simplify
fx
simplify
collapse
simplify
fx
resub
eliminate -1
resub
source script.rugged
reduce_depth
source script.rugged
simplify
reduce_depth
reduce_depth
full_simplify
resub
espresso
collapse
fx
espresso
resub
eliminate -1
simplify
resub
full_simplify
collapse
espresso
eliminate -1
espresso
simplify
fx
espresso
espresso
collapse
resub
sweep
fx
simplify
full_simplify
resub
full_simplify
simplify
espresso
simplify
sweep
resub
espresso
source script.rugged
resub
collapse
collapse
sweep
reduce_depth
eliminate -1
fx
sweep
collapse
simplify
fx
full_simplify
collapse
fx
espresso
full_simplify
sweep
espresso
fx
sweep
resub
reduce_depth
sweep
resub
full_simplify
full_simplify
fx
fx
source script.rugged
sweep
simplify
resub
reduce_depth
sweep
collapse
espresso
collapse
resub
simplify
collapse
collapse
reduce_depth
eliminate -1
eliminate -1
simplify
eliminate -1
fx
full_simplify
resub
reduce_depth
full_simplify
espresso
resub
resub
espresso
source script.rugged
full_simplify
eliminate -1
full_simplify
resub
sweep
sweep
full_simplify
eliminate -1
eliminate -1
collapse
fx
eliminate -1
source script.rugged
simplify
sweep
simplify
resub
resub
full_simplify
source script.rugged
collapse
fx
sweep
reduce_depth
source script.rugged
simplify
reduce_depth
fx
eliminate -1
collapse
source script.rugged
source script.rugged
full_simplify
reduce_depth
source script.rugged
eliminate -1
source script.rugged
sweep
collapse
reduce_depth
source script.rugged
reduce_depth
reduce_depth
collapse
fx
simplify
collapse
resub
espresso
reduce_depth
source script.rugged
eliminate -1
full_simplify
resub
espresso
reduce_depth
resub
fx
source script.rugged
fx
simplify
fx
resub
source script.rugged
collapse
fx
espresso
full_simplify
reduce_depth
fx
eliminate -1
resub
reduce_depth
espresso
eliminate -1
fx
espresso
eliminate -1
fx
source script.rugged
fx
espresso
sweep
sweep
collapse
collapse
collapse
sweep
fx
eliminate -1
collapse
simplify
resub
espresso
collapse
sweep
resub
sweep
full_simplify
sweep
collapse
sweep
source script.rugged
full_simplify
source script.rugged
resub
espresso
resub
reduce_depth
reduce_depth
reduce_depth
source script.rugged
sweep
espresso
source script.rugged
simplify
full_simplify
source script.rugged
full_simplify
sweep
source script.rugged
full_simplify
simplify
source script.rugged
full_simplify
simplify
espresso
simplify
resub
simplify
reduce_depth
collapse
collapse
sweep
collapse
fx
espresso
sweep
full_simplify
espresso
resub
full_simplify
reduce_depth
collapse
sweep
full_simplify
collapse
full_simplify
full_simplify
sweep
eliminate -1
reduce_depth
resub
reduce_depth
resub
source script.rugged
espresso
sweep
resub
eliminate -1
eliminate -1
reduce_depth
eliminate -1
espresso
full_simplify
collapse
collapse
espresso
collapse
full_simplify
fx
eliminate -1
sweep
sweep
eliminate -1
espresso
resub
resub
source script.rugged
full_simplify
sweep
espresso
collapse
full_simplify
fx
source script.rugged
fx
resub
eliminate -1
resub
collapse
eliminate -1
simplify
resub
eliminate -1
fx
eliminate -1
fx
eliminate -1
espresso
full_simplify
resub
sweep
resub
sweep
collapse
resub
source script.rugged
fx
full_simplify
simplify
source script.rugged
full_simplify
resub
simplify
simplify
eliminate -1
reduce_depth
full_simplify
collapse
simplify
collapse
collapse
full_simplify
fx
resub
resub
simplify
resub
full_simplify
source script.rugged
simplify
reduce_depth
source script.rugged
simplify
resub
espresso
fx
collapse
full_simplify
fx
collapse
collapse
collapse
simplify
sweep
simplify
full_simplify
simplify
espresso
source script.rugged
reduce_depth
source script.rugged
fx
fx
resub
eliminate -1
source script.rugged
sweep
espresso
full_simplify
resub
resub
source script.rugged
collapse
sweep
collapse
espresso
fx
resub
resub
collapse
reduce_depth
collapse
reduce_depth
collapse
full_simplify
reduce_depth
espresso
fx
full_simplify
fx
fx
resub
resub
eliminate -1
full_simplify
espresso
full_simplify
fx
espresso
espresso
fx
reduce_depth
fx
collapse
eliminate -1
fx
simplify
full_simplify
sweep
espresso
full_simplify
simplify
source script.rugged
resub
source script.rugged
eliminate -1
resub
full_simplify
source script.rugged
collapse
source script.rugged
write_blif min_fsm.blif
